In [2]:
from ConvLayer import *

In [3]:
input_array = np.arange(25).reshape(5, 5)
kernel_array = np.ones((2, 2))

In [4]:
conv(input_array, kernel_array, 1, 0)

array([[12., 16., 20., 24.],
       [32., 36., 40., 44.],
       [52., 56., 60., 64.],
       [72., 76., 80., 84.]])

In [5]:
input_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
pad(input_array, 1)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  2.,  3.,  4.,  0.],
       [ 0.,  5.,  6.,  7.,  8.,  9.,  0.],
       [ 0., 10., 11., 12., 13., 14.,  0.],
       [ 0., 15., 16., 17., 18., 19.,  0.],
       [ 0., 20., 21., 22., 23., 24.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])